"""
TTKIA Client – Main entry point for the SDK.

Uses /query_complete REST endpoint for all queries.
Supports both synchronous and asynchronous interfaces.
Authentication via API Key (X-API-Key) or Bearer JWT token.
Configuration can be loaded from ~/.ttkia/config.json (same as CLI).
"""

from __future__ import annotations

import asyncio
import json
import mimetypes
import time
from pathlib import Path
from typing import Any, Dict, List, Optional
from datetime import datetime, timezone

import httpx

from ttkia_sdk.models import (
    AuthenticationError,
    Conversation,
    ConversationSummary,
    FeedbackResult,
    HealthStatus,
    InsufficientScopeError,
    MCPToolResult,
    NotFoundError,
    QueryResponse,
    RateLimitError,
    Source,
    TimingInfo,
    TokenUsage,
    TTKIAError,
)

_DEFAULT_TIMEOUT = 120.0
_API_KEY_PREFIX = "ttkia_sk_"
_CONFIG_FILE = Path.home() / ".ttkia" / "config.json"

# Prefijo con el que main.py monta src/routes/conversation_routes.py:
#     app.include_router(conversation_router, prefix="/conversations", ...)
# Si se cambia el prefijo en el backend, basta con tocar esta constante.
_CONV = "/conversations"


def _load_config_file() -> dict:
    """Load configuration from ~/.ttkia/config.json if it exists."""
    if _CONFIG_FILE.exists():
        try:
            return json.loads(_CONFIG_FILE.read_text())
        except (json.JSONDecodeError, OSError):
            return {}
    return {}


class _BearerAuth(httpx.Auth):
    """httpx Auth handler that injects Bearer token on every request, including redirects."""

    def __init__(self, token: str):
        self.token = token

    def auth_flow(self, request):
        request.headers["Authorization"] = f"Bearer {self.token}"
        yield request


class TTKIAClient:
    """
    Official TTKIA Python client.

    All queries go through the /query_complete REST endpoint which
    executes the full pipeline and returns the consolidated response.

    Authentication:
        - API Key: ``TTKIAClient(base_url="...", api_key="ttkia_sk_...")``
        - Bearer Token: ``TTKIAClient(base_url="...", bearer_token="eyJ...")``
        - From config file: ``TTKIAClient()`` (uses ~/.ttkia/config.json)

    When no explicit base_url/api_key/bearer_token is provided, the client
    reads from ``~/.ttkia/config.json`` (generated by ``ttkia config``).
    Environment variables ``TTKIA_URL``, ``TTKIA_API_KEY``, ``TTKIA_TOKEN``
    take priority over the config file.

    Usage::

        # Explicit credentials
        client = TTKIAClient(base_url="https://...", api_key="ttkia_sk_...")

        # From config file (after running ttkia config)
        client = TTKIAClient()

        response = client.query("What is BGP?")
        print(response.text)
        client.close()

    Or as context manager::

        with TTKIAClient() as client:
            response = client.query("What is BGP?")
            print(response.text)
    """

    def __init__(
        self,
        base_url: Optional[str] = None,
        *,
        bearer_token: Optional[str] = None,
        api_key: Optional[str] = None,
        timeout: float = _DEFAULT_TIMEOUT,
        verify_ssl: bool = True,
    ):
        # ── Resolve config: explicit args > env vars > config file ────
        import os

        file_config = _load_config_file()

        resolved_url = base_url or os.environ.get("TTKIA_URL") or file_config.get("url")
        resolved_token = bearer_token or os.environ.get("TTKIA_TOKEN") or file_config.get("token")
        resolved_key = api_key or os.environ.get("TTKIA_API_KEY") or file_config.get("api_key")

        # Timeout and SSL from config file if not explicitly set
        if timeout == _DEFAULT_TIMEOUT and "timeout" in file_config:
            timeout = float(file_config["timeout"])
        if verify_ssl is True and "verify_ssl" in file_config:
            verify_ssl = file_config["verify_ssl"]

        if not resolved_url:
            raise TTKIAError(
                "No TTKIA URL configured. "
                "Pass base_url=, set TTKIA_URL env var, or run: ttkia config --url <URL> --api-key <KEY>"
            )

        if not resolved_token and not resolved_key:
            raise TTKIAError(
                "No authentication configured. "
                "Pass api_key= or bearer_token=, set TTKIA_API_KEY env var, "
                "or run: ttkia config --api-key ttkia_sk_..."
            )

        self._base_url = resolved_url.rstrip("/")
        self._bearer_token = resolved_token
        self._api_key = resolved_key

        # ── HTTP clients ──────────────────────────────────────────────
        common = dict(
            base_url=self._base_url,
            timeout=timeout,
            verify=verify_ssl,
            headers={"Accept": "application/json"},
        )

        auth = _BearerAuth(self._bearer_token) if self._bearer_token else None

        self._http = httpx.AsyncClient(**common, auth=auth)
        self._http_sync = httpx.Client(**common, auth=auth)

        if self._api_key:
            self._http.headers["X-API-Key"] = self._api_key
            self._http_sync.headers["X-API-Key"] = self._api_key

    # ──────────────────────────────────────────────────────────
    # CONTEXT MANAGER
    # ──────────────────────────────────────────────────────────

    def __enter__(self):
        return self

    def __exit__(self, *args):
        self.close()

    async def __aenter__(self):
        return self

    async def __aexit__(self, *args):
        await self.aclose()

    def close(self):
        self._http_sync.close()
        try:
            loop = asyncio.get_event_loop()
            if loop.is_running():
                loop.create_task(self._http.aclose())
            else:
                loop.run_until_complete(self._http.aclose())
        except RuntimeError:
            pass

    async def aclose(self):
        await self._http.aclose()
        self._http_sync.close()

    # ──────────────────────────────────────────────────────────
    # ERROR HANDLING
    # ──────────────────────────────────────────────────────────

    @staticmethod
    def _handle_error(resp: httpx.Response):
        if resp.is_success:
            return

        code = resp.status_code
        try:
            body = resp.json()
            msg = body.get("detail") or body.get("message") or resp.text
        except Exception:
            msg = resp.text

        if code == 401:
            raise AuthenticationError(str(msg), code)
        if code == 403:
            raise InsufficientScopeError(str(msg), code)
        if code == 404:
            raise NotFoundError(str(msg), code)
        if code == 429:
            retry = int(resp.headers.get("Retry-After", "60"))
            raise RateLimitError(str(msg), retry_after=retry, status_code=code)
        raise TTKIAError(str(msg), code)

    # ──────────────────────────────────────────────────────────
    # RESPONSE PARSING
    # ──────────────────────────────────────────────────────────

    @staticmethod
    def _parse_query_response(data: dict, fallback_query: str = "") -> QueryResponse:
        """Parse backend JSON into a typed QueryResponse."""
        timing_raw = data.get("timing", [])
        if isinstance(timing_raw, dict):
            timing_raw = [{k: v} for k, v in timing_raw.items()]

        # Parse MCP tool results
        mcp_tools_raw = data.get("mcp_tools") or []
        mcp_tools = []
        for t in mcp_tools_raw:
            if isinstance(t, dict):
                mcp_tools.append(MCPToolResult(
                    name=t.get("name", ""),
                    status=t.get("status", ""),
                    args=t.get("args", {}),
                    result=t.get("result"),
                ))

        return QueryResponse(
            success=data.get("success", False),
            conversation_id=data.get("conversation_id", ""),
            message_id=data.get("message_id", ""),
            query=data.get("query", fallback_query),
            response_text=data.get("response_text", ""),
            confidence=data.get("confidence"),
            recommended_response=data.get("recommended_response"),
            query_extended=data.get("query_extended"),
            token_usage=TokenUsage(
                input_tokens=data.get("token_counts", {}).get("input", 0),
                output_tokens=data.get("token_counts", {}).get("output", 0),
            ),
            timing=TimingInfo(raw=timing_raw),
            inferred_environments=data.get("inferred_environments", []),
            docs=[Source(**d) for d in data.get("docs", [])],
            webs=[Source(**w) for w in data.get("webs", [])],
            links=data.get("links", []),
            thinking_process=data.get("thinking_process", []),
            mcp_tools=mcp_tools,
            follow_ups=data.get("follow_ups", []),
            error=data.get("error"),
        )

    # ──────────────────────────────────────────────────────────
    # HEALTH
    # ──────────────────────────────────────────────────────────

    async def ahealth(self) -> HealthStatus:
        """Check TTKIA service health (async)."""
        resp = await self._http.get("/health")
        self._handle_error(resp)
        return HealthStatus(**resp.json())

    def health(self) -> HealthStatus:
        """Check TTKIA service health (sync)."""
        resp = self._http_sync.get("/health")
        self._handle_error(resp)
        return HealthStatus(**resp.json())

    # ──────────────────────────────────────────────────────────
    # QUERY (via /query_complete)
    # ──────────────────────────────────────────────────────────

    async def aquery(
        self,
        query: str,
        *,
        conversation_id: Optional[str] = None,
        prompt: str = "default",
        style: str = "concise",
        web_search: bool = False,
        sources: Optional[List[str]] = None,
        teacher_mode: bool = False,
        title: Optional[str] = None,
        attached_files: Optional[List[dict]] = None,
        attached_urls: Optional[List[dict]] = None,
    ) -> QueryResponse:
        """Send a query via /query_complete and get the full response (async)."""
        payload = {
            "query": query,
            "prompt": prompt,
            "style": style,
            "web_search": web_search,
            "teacher_mode": teacher_mode,
            "sources": sources or [],
            "attached_files": attached_files or [],
            "attached_urls": attached_urls or [],
        }
        if conversation_id:
            payload["conversation_id"] = conversation_id
        if title:
            payload["title"] = title

        resp = await self._http.post("/query_complete", json=payload)
        self._handle_error(resp)
        data = resp.json()
        return self._parse_query_response(data, fallback_query=query)

    def query(
        self,
        query: str,
        *,
        conversation_id: Optional[str] = None,
        prompt: str = "default",
        style: str = "concise",
        web_search: bool = False,
        sources: Optional[List[str]] = None,
        teacher_mode: bool = False,
        title: Optional[str] = None,
        attached_files: Optional[List[dict]] = None,
        attached_urls: Optional[List[dict]] = None,
    ) -> QueryResponse:
        """Send a query via /query_complete and get the full response (sync)."""
        payload = {
            "query": query,
            "prompt": prompt,
            "style": style,
            "web_search": web_search,
            "teacher_mode": teacher_mode,
            "sources": sources or [],
            "attached_files": attached_files or [],
            "attached_urls": attached_urls or [],
        }
        if conversation_id:
            payload["conversation_id"] = conversation_id
        if title:
            payload["title"] = title

        resp = self._http_sync.post("/query_complete", json=payload)
        self._handle_error(resp)
        data = resp.json()
        return self._parse_query_response(data, fallback_query=query)

    # ──────────────────────────────────────────────────────────
    # CODE AGENT QUERY (via /code/query, lightweight single-call)
    # ──────────────────────────────────────────────────────────

    def code_query(
        self,
        query: str,
        *,
        conversation_id: Optional[str] = None,
        title: Optional[str] = None,
    ) -> QueryResponse:
        """Send a code agent query via /code/query (lightweight, single LLM call)."""
        payload = {"query": query}
        if conversation_id:
            payload["conversation_id"] = conversation_id
        if title:
            payload["title"] = title

        resp = self._http_sync.post("/code/query", json=payload)
        self._handle_error(resp)
        data = resp.json()

        return QueryResponse(
            success=data.get("success", False),
            conversation_id=data.get("conversation_id", ""),
            message_id=data.get("message_id", ""),
            query=query,
            response_text=data.get("response_text", ""),
            confidence=None,
            token_usage=TokenUsage(
                input_tokens=data.get("token_counts", {}).get("input", 0),
                output_tokens=data.get("token_counts", {}).get("output", 0),
            ),
            timing=TimingInfo(raw=[]),
            error=data.get("error"),
        )

    def code_query_stream(
        self,
        query: str,
        *,
        conversation_id: Optional[str] = None,
        title: Optional[str] = None,
    ):
        '''
        Stream a code agent query via /code/stream (SSE).

        Yields:
            dict: Events with 'type' and 'content' keys.
                  Types: 'mcp', 'text', 'done', 'error'
        '''
        payload = {"query": query}
        if conversation_id:
            payload["conversation_id"] = conversation_id
        if title:
            payload["title"] = title

        with self._http_sync.stream("POST", "/code/stream", json=payload) as resp:
            if resp.status_code != 200:
                raise TTKIAError(f"Stream failed: {resp.status_code}", resp.status_code)

            for line in resp.iter_lines():
                if line.startswith("data: "):
                    try:
                        event = json.loads(line[6:])
                        yield event
                    except json.JSONDecodeError:
                        continue

    # ──────────────────────────────────────────────────────────
    # CONVERSATIONS
    #
    # API REST (src/routes/conversation_routes.py):
    #     GET    /conversations                       lista (sin mensajes)
    #     POST   /conversations                       crear
    #     GET    /conversations/search?q=             buscar
    #     GET    /conversations/{id}                  conversación completa
    #     GET    /conversations/{id}/info             + sharing_info
    #     PATCH  /conversations/{id}                  renombrar / pin
    #     DELETE /conversations/{id}                  borrar
    #     GET    /conversations/{id}/export           ZIP
    #     DELETE /conversations/{id}/messages/{mid}   borrar par Q&A
    #
    # Sustituyen a los antiguos /env (para listar), /conversation-info,
    # /new-workspace, /delete-conversation, /forget, /export-conversation
    # y /delete-qa, que ya no existen en el backend.
    # ──────────────────────────────────────────────────────────

    async def alist_conversations(self) -> List[ConversationSummary]:
        """Lista de conversaciones: metadatos y contadores, sin mensajes (async)."""
        resp = await self._http.get(_CONV)
        self._handle_error(resp)
        return [ConversationSummary(**c) for c in resp.json().get("conversations", [])]

    def list_conversations(self) -> List[ConversationSummary]:
        """Lista de conversaciones: metadatos y contadores, sin mensajes (sync)."""
        resp = self._http_sync.get(_CONV)
        self._handle_error(resp)
        return [ConversationSummary(**c) for c in resp.json().get("conversations", [])]

    async def asearch_conversations(self, q: str) -> List[dict]:
        """Busca en título, resumen y contenido de mensajes (async). Mínimo 2 caracteres."""
        resp = await self._http.get(f"{_CONV}/search", params={"q": q})
        self._handle_error(resp)
        return resp.json().get("matches", [])

    def search_conversations(self, q: str) -> List[dict]:
        """Busca en título, resumen y contenido de mensajes (sync). Mínimo 2 caracteres."""
        resp = self._http_sync.get(f"{_CONV}/search", params={"q": q})
        self._handle_error(resp)
        return resp.json().get("matches", [])

    async def aget_conversation(self, conversation_id: str) -> Conversation:
        """Conversación completa: mensajes, adjuntos y referencias web (async)."""
        resp = await self._http.get(f"{_CONV}/{conversation_id}")
        self._handle_error(resp)
        return Conversation(**resp.json())

    def get_conversation(self, conversation_id: str) -> Conversation:
        """Conversación completa: mensajes, adjuntos y referencias web (sync)."""
        resp = self._http_sync.get(f"{_CONV}/{conversation_id}")
        self._handle_error(resp)
        return Conversation(**resp.json())

    async def aget_conversation_info(self, conversation_id: str) -> dict:
        """
        Igual que aget_conversation() pero incluyendo `sharing_info` (async).

        Devuelve el dict crudo: `sharing_info` no forma parte del modelo
        Conversation y se perdería al tipar.
        """
        resp = await self._http.get(f"{_CONV}/{conversation_id}/info")
        self._handle_error(resp)
        return resp.json()

    def get_conversation_info(self, conversation_id: str) -> dict:
        """
        Igual que get_conversation() pero incluyendo `sharing_info` (sync).

        Devuelve el dict crudo: `sharing_info` no forma parte del modelo
        Conversation y se perdería al tipar.
        """
        resp = self._http_sync.get(f"{_CONV}/{conversation_id}/info")
        self._handle_error(resp)
        return resp.json()

    async def acreate_conversation(self, title: str = "SDK Conversation") -> str:
        """Crea una conversación vacía y devuelve su id (async)."""
        resp = await self._http.post(_CONV, json={"title": title})
        self._handle_error(resp)
        return resp.json().get("conversation_id", "")

    def create_conversation(self, title: str = "SDK Conversation") -> str:
        """Crea una conversación vacía y devuelve su id (sync)."""
        resp = self._http_sync.post(_CONV, json={"title": title})
        self._handle_error(resp)
        return resp.json().get("conversation_id", "")

    async def aupdate_conversation(
        self,
        conversation_id: str,
        *,
        title: Optional[str] = None,
        pinned: Optional[bool] = None,
    ) -> dict:
        """
        Actualización parcial de una conversación: título y/o pin (async).

        Solo se envían los campos indicados. No pasar ninguno da error 400.
        """
        payload: Dict[str, Any] = {}
        if title is not None:
            payload["title"] = title
        if pinned is not None:
            payload["pinned"] = pinned
        if not payload:
            raise TTKIAError("Nothing to update: pass title= and/or pinned=")

        resp = await self._http.patch(f"{_CONV}/{conversation_id}", json=payload)
        self._handle_error(resp)
        return resp.json()

    def update_conversation(
        self,
        conversation_id: str,
        *,
        title: Optional[str] = None,
        pinned: Optional[bool] = None,
    ) -> dict:
        """
        Actualización parcial de una conversación: título y/o pin (sync).

        Solo se envían los campos indicados. No pasar ninguno da error 400.
        """
        payload: Dict[str, Any] = {}
        if title is not None:
            payload["title"] = title
        if pinned is not None:
            payload["pinned"] = pinned
        if not payload:
            raise TTKIAError("Nothing to update: pass title= and/or pinned=")

        resp = self._http_sync.patch(f"{_CONV}/{conversation_id}", json=payload)
        self._handle_error(resp)
        return resp.json()

    def rename_conversation(self, conversation_id: str, title: str) -> dict:
        """Atajo sobre update_conversation() para renombrar."""
        return self.update_conversation(conversation_id, title=title)

    def pin_conversation(self, conversation_id: str, pinned: bool = True) -> dict:
        """Atajo sobre update_conversation() para fijar/desfijar."""
        return self.update_conversation(conversation_id, pinned=pinned)

    async def adelete_conversation(self, conversation_id: str) -> bool:
        """
        Elimina una conversación: MongoDB + Qdrant + ficheros (async).

        Acepta JWT de sesión o API Key con scope 'conversations'.
        """
        resp = await self._http.delete(f"{_CONV}/{conversation_id}")
        self._handle_error(resp)
        return resp.json().get("success", False)

    def delete_conversation(self, conversation_id: str) -> bool:
        """
        Elimina una conversación: MongoDB + Qdrant + ficheros (sync).

        Acepta JWT de sesión o API Key con scope 'conversations'.
        """
        resp = self._http_sync.delete(f"{_CONV}/{conversation_id}")
        self._handle_error(resp)
        return resp.json().get("success", False)

    async def adelete_message_pair(self, conversation_id: str, message_id: str) -> bool:
        """Borra el par pregunta-respuesta que comparte message_id (async)."""
        resp = await self._http.delete(f"{_CONV}/{conversation_id}/messages/{message_id}")
        self._handle_error(resp)
        return resp.json().get("success", False)

    def delete_message_pair(self, conversation_id: str, message_id: str) -> bool:
        """Borra el par pregunta-respuesta que comparte message_id (sync)."""
        resp = self._http_sync.delete(f"{_CONV}/{conversation_id}/messages/{message_id}")
        self._handle_error(resp)
        return resp.json().get("success", False)

    def export_conversation(self, conversation_id: str, output_path: str):
        """Exporta la conversación como ZIP con un markdown dentro (sync)."""
        resp = self._http_sync.get(f"{_CONV}/{conversation_id}/export")
        self._handle_error(resp)
        with open(output_path, "wb") as f:
            f.write(resp.content)

    async def aexport_conversation(self, conversation_id: str, output_path: str):
        """Exporta la conversación como ZIP con un markdown dentro (async)."""
        resp = await self._http.get(f"{_CONV}/{conversation_id}/export")
        self._handle_error(resp)
        with open(output_path, "wb") as f:
            f.write(resp.content)

    # ──────────────────────────────────────────────────────────
    # ENVIRONMENTS / PROMPTS / STYLES
    # ──────────────────────────────────────────────────────────

    async def aget_environments(self) -> List[str]:
        resp = await self._http.post("/env")
        self._handle_error(resp)
        return resp.json().get("environment", [])

    def get_environments(self) -> List[str]:
        resp = self._http_sync.post("/env")
        self._handle_error(resp)
        return resp.json().get("environment", [])

    async def aget_prompts(self) -> List[dict]:
        resp = await self._http.post("/env")
        self._handle_error(resp)
        return resp.json().get("prompts", [])

    def get_prompts(self) -> List[dict]:
        resp = self._http_sync.post("/env")
        self._handle_error(resp)
        return resp.json().get("prompts", [])

    async def aget_styles(self) -> List[dict]:
        resp = await self._http.post("/env")
        self._handle_error(resp)
        return resp.json().get("styles", [])

    def get_styles(self) -> List[dict]:
        resp = self._http_sync.post("/env")
        self._handle_error(resp)
        return resp.json().get("styles", [])

    # ──────────────────────────────────────────────────────────
    # FEEDBACK
    # ──────────────────────────────────────────────────────────

    @staticmethod
    def _build_feedback_payload(
        conversation_id: str,
        message_id: str,
        score: int,
        query: str = "",
        answer: str = "",
        prompt: str = "default",
        style: str = "concise",
    ) -> dict:
        """
        Construye el payload de FeedbackMessage que espera POST /feedback.

        El modelo del backend exige campos obligatorios que el SDK no siempre
        conoce (username, client_info, timestamps...). El backend sobrescribe
        `username` con el usuario autenticado, por lo que se envía vacío; el
        resto se rellena con valores neutros.

        Nota: /feedback/score no existe — el router de feedback solo expone
        endpoints de analítica (insights, confidence_by_environment).
        """
        now = datetime.now(timezone.utc).isoformat()
        return {
            "query": query,
            "answer": answer,
            "prompt": prompt,
            "style": style,
            "timestamp": now,
            "feedback": score > 0,
            "conversation_id": conversation_id,
            "message_id": message_id,
            "username": "",           # el backend lo sustituye por el usuario real
            "teacher_mode": False,
            "selected_sources": [],
            "retrieved_docs": [],
            "retrieved_links": [],
            "retrieved_webs": [],
            "attachments": {"files": [], "urls": []},
            "client_timestamp": now,
            "client_timezone": "UTC",
            "client_info": {"source": "ttkia_sdk"},
            "inferred_environments": [],
        }

    @staticmethod
    def _parse_feedback_result(data: dict) -> FeedbackResult:
        """El backend devuelve {"status": "success", "message": "..."}."""
        return FeedbackResult(
            success=(data.get("status") == "success"),
            message=data.get("message", ""),
        )

    async def asend_feedback(
        self,
        conversation_id: str,
        message_id: str,
        score: int,
        *,
        query: str = "",
        answer: str = "",
        prompt: str = "default",
        style: str = "concise",
    ) -> FeedbackResult:
        """
        Envía feedback sobre una respuesta (async).

        Pasa `query` y `answer` si los tienes (del QueryResponse) para que el
        feedback quede con contexto en el análisis RAG.
        """
        payload = self._build_feedback_payload(
            conversation_id, message_id, score, query, answer, prompt, style
        )
        resp = await self._http.post("/feedback", json=payload)
        self._handle_error(resp)
        return self._parse_feedback_result(resp.json())

    def send_feedback(
        self,
        conversation_id: str,
        message_id: str,
        score: int,
        *,
        query: str = "",
        answer: str = "",
        prompt: str = "default",
        style: str = "concise",
    ) -> FeedbackResult:
        """
        Envía feedback sobre una respuesta (sync).

        Pasa `query` y `answer` si los tienes (del QueryResponse) para que el
        feedback quede con contexto en el análisis RAG.
        """
        payload = self._build_feedback_payload(
            conversation_id, message_id, score, query, answer, prompt, style
        )
        resp = self._http_sync.post("/feedback", json=payload)
        self._handle_error(resp)
        return self._parse_feedback_result(resp.json())

    # ──────────────────────────────────────────────────────────
    # ATTACHMENTS
    # ──────────────────────────────────────────────────────────

    def upload_attachment(
        self,
        file_path: str,
        conversation_id: str,
        *,
        wait_for_embedding: bool = True,
        poll_interval: float = 2.0,
        poll_timeout: float = 60.0,
    ) -> dict:
        """
        Sube un fichero al backend y devuelve el metadata para usar en query().

        Para documentos (PDF, DOCX, TXT, CSV, etc.) el backend lanza el
        embedding en background y devuelve status='processing'. Por defecto,
        este método espera (poll a GET /conversations/{id}) hasta que el adjunto
        cambie a 'completed' antes de devolver.

        Para imágenes (PNG, JPG, etc.) el backend devuelve status='completed'
        inmediatamente.

        Args:
            file_path: Ruta local al fichero.
            conversation_id: ID de la conversación destino.
            wait_for_embedding: Si True (default), espera a que el embedding
                                termine antes de devolver.
            poll_interval: Segundos entre polls (default 2.0).
            poll_timeout: Tiempo máximo de espera en segundos (default 60.0).

        Returns:
            dict con path, name, size, type, status para pasar en attached_files.
        """
        path = Path(file_path)
        mime_type, _ = mimetypes.guess_type(str(path))
        mime_type = mime_type or "application/octet-stream"

        with open(path, "rb") as f:
            resp = self._http_sync.post(
                "/chat-upload",
                files={"file": (path.name, f, mime_type)},
                data={"conversation_id": conversation_id},
            )
        self._handle_error(resp)
        data = resp.json()
        attachment = {
            "path": data["path"],
            "name": data["name"],
            "size": data["size"],
            "type": data["type"],
            "status": data.get("status", "completed"),
        }

        if wait_for_embedding and attachment["status"] == "processing":
            deadline = time.monotonic() + poll_timeout
            while time.monotonic() < deadline:
                time.sleep(poll_interval)
                conv = self.get_conversation(conversation_id)
                for att in (conv.file_attachments or []):
                    if att.get("name") == attachment["name"]:
                        attachment["status"] = att.get("status", "processing")
                        break
                if attachment["status"] != "processing":
                    break

        return attachment

    async def aupload_attachment(
        self,
        file_path: str,
        conversation_id: str,
        *,
        wait_for_embedding: bool = True,
        poll_interval: float = 2.0,
        poll_timeout: float = 60.0,
    ) -> dict:
        """Versión async de upload_attachment."""
        path = Path(file_path)
        mime_type, _ = mimetypes.guess_type(str(path))
        mime_type = mime_type or "application/octet-stream"

        with open(path, "rb") as f:
            content = f.read()

        resp = await self._http.post(
            "/chat-upload",
            files={"file": (path.name, content, mime_type)},
            data={"conversation_id": conversation_id},
        )
        self._handle_error(resp)
        data = resp.json()
        attachment = {
            "path": data["path"],
            "name": data["name"],
            "size": data["size"],
            "type": data["type"],
            "status": data.get("status", "completed"),
        }

        if wait_for_embedding and attachment["status"] == "processing":
            deadline = time.monotonic() + poll_timeout
            while time.monotonic() < deadline:
                await asyncio.sleep(poll_interval)
                conv = await self.aget_conversation(conversation_id)
                for att in (conv.file_attachments or []):
                    if att.get("name") == attachment["name"]:
                        attachment["status"] = att.get("status", "processing")
                        break
                if attachment["status"] != "processing":
                    break

        return attachment

    # ──────────────────────────────────────────────────────────
    # URL INDEXING
    # ──────────────────────────────────────────────────────────

    def index_url(
        self,
        url: str,
        conversation_id: str,
    ) -> List[dict]:
        """
        Indexa una URL como referencia web de la conversación vía /process-urls.

        El backend descarga el contenido, lo embebe en Qdrant como referencia
        web de la conversación, y devuelve el metadata para pasarlo en
        attached_urls de query().

        El dominio debe estar en la lista permitida del backend
        (cisco.com, fortinet.com, paloaltonetworks.com, microsoft.com,
        telefonica.com, kubernetes.io, docker.com, etc.). Si no, devuelve
        lista vacía.

        Args:
            url: URL a indexar.
            conversation_id: ID de la conversación destino (obligatorio).

        Returns:
            Lista de dicts con path ('web://...'), name, type, metadata.
            Lista vacía si la URL fue bloqueada por seguridad.
        """
        resp = self._http_sync.post(
            "/process-urls",
            json={"query": url, "conversation_id": conversation_id},
        )
        self._handle_error(resp)
        data = resp.json()
        return data.get("attachments", [])

    async def aindex_url(
        self,
        url: str,
        conversation_id: str,
    ) -> List[dict]:
        """Versión async de index_url."""
        resp = await self._http.post(
            "/process-urls",
            json={"query": url, "conversation_id": conversation_id},
        )
        self._handle_error(resp)
        data = resp.json()
        return data.get("attachments", [])