"""
TTKIA Client – Main entry point for the SDK.

Uses /query_complete REST endpoint for all queries.
Supports both synchronous and asynchronous interfaces.
Authentication via API Key (X-API-Key) or Bearer JWT token.
Configuration can be loaded from ~/.ttkia/config.json (same as CLI).
"""

from __future__ import annotations

import asyncio
import json
from pathlib import Path
from typing import Any, Dict, List, Optional
from datetime import datetime, timezone

import httpx

from ttkia_sdk.models import (
    AuthenticationError,
    Conversation,
    ConversationSummary,
    FeedbackResult,
    HealthStatus,
    InsufficientScopeError,
    MCPToolResult,
    NotFoundError,
    QueryResponse,
    RateLimitError,
    Source,
    TimingInfo,
    TokenUsage,
    TTKIAError,
)

_DEFAULT_TIMEOUT = 120.0
_API_KEY_PREFIX = "ttkia_sk_"
_CONFIG_FILE = Path.home() / ".ttkia" / "config.json"


def _load_config_file() -> dict:
    """Load configuration from ~/.ttkia/config.json if it exists."""
    if _CONFIG_FILE.exists():
        try:
            return json.loads(_CONFIG_FILE.read_text())
        except (json.JSONDecodeError, OSError):
            return {}
    return {}


class _BearerAuth(httpx.Auth):
    """httpx Auth handler that injects Bearer token on every request, including redirects."""

    def __init__(self, token: str):
        self.token = token

    def auth_flow(self, request):
        request.headers["Authorization"] = f"Bearer {self.token}"
        yield request


class TTKIAClient:
    """
    Official TTKIA Python client.

    All queries go through the /query_complete REST endpoint which
    executes the full pipeline and returns the consolidated response.

    Authentication:
        - API Key: ``TTKIAClient(base_url="...", api_key="ttkia_sk_...")``
        - Bearer Token: ``TTKIAClient(base_url="...", bearer_token="eyJ...")``
        - From config file: ``TTKIAClient()`` (uses ~/.ttkia/config.json)

    When no explicit base_url/api_key/bearer_token is provided, the client
    reads from ``~/.ttkia/config.json`` (generated by ``ttkia config``).
    Environment variables ``TTKIA_URL``, ``TTKIA_API_KEY``, ``TTKIA_TOKEN``
    take priority over the config file.

    Usage::

        # Explicit credentials
        client = TTKIAClient(base_url="https://...", api_key="ttkia_sk_...")

        # From config file (after running ttkia config)
        client = TTKIAClient()

        response = client.query("What is BGP?")
        print(response.text)
        client.close()

    Or as context manager::

        with TTKIAClient() as client:
            response = client.query("What is BGP?")
            print(response.text)
    """

    def __init__(
        self,
        base_url: Optional[str] = None,
        *,
        bearer_token: Optional[str] = None,
        api_key: Optional[str] = None,
        timeout: float = _DEFAULT_TIMEOUT,
        verify_ssl: bool = True,
    ):
        # ── Resolve config: explicit args > env vars > config file ────
        import os

        file_config = _load_config_file()

        resolved_url = base_url or os.environ.get("TTKIA_URL") or file_config.get("url")
        resolved_token = bearer_token or os.environ.get("TTKIA_TOKEN") or file_config.get("token")
        resolved_key = api_key or os.environ.get("TTKIA_API_KEY") or file_config.get("api_key")

        # Timeout and SSL from config file if not explicitly set
        if timeout == _DEFAULT_TIMEOUT and "timeout" in file_config:
            timeout = float(file_config["timeout"])
        if verify_ssl is True and "verify_ssl" in file_config:
            verify_ssl = file_config["verify_ssl"]

        if not resolved_url:
            raise TTKIAError(
                "No TTKIA URL configured. "
                "Pass base_url=, set TTKIA_URL env var, or run: ttkia config --url <URL> --api-key <KEY>"
            )

        if not resolved_token and not resolved_key:
            raise TTKIAError(
                "No authentication configured. "
                "Pass api_key= or bearer_token=, set TTKIA_API_KEY env var, "
                "or run: ttkia config --api-key ttkia_sk_..."
            )

        self._base_url = resolved_url.rstrip("/")
        self._bearer_token = resolved_token
        self._api_key = resolved_key

        # ── HTTP clients ──────────────────────────────────────────────
        common = dict(
            base_url=self._base_url,
            timeout=timeout,
            verify=verify_ssl,
            headers={"Accept": "application/json"},
        )

        auth = _BearerAuth(self._bearer_token) if self._bearer_token else None

        self._http = httpx.AsyncClient(**common, auth=auth)
        self._http_sync = httpx.Client(**common, auth=auth)

        if self._api_key:
            self._http.headers["X-API-Key"] = self._api_key
            self._http_sync.headers["X-API-Key"] = self._api_key

    # ──────────────────────────────────────────────────────────
    # CONTEXT MANAGER
    # ──────────────────────────────────────────────────────────

    def __enter__(self):
        return self

    def __exit__(self, *args):
        self.close()

    async def __aenter__(self):
        return self

    async def __aexit__(self, *args):
        await self.aclose()

    def close(self):
        self._http_sync.close()
        try:
            loop = asyncio.get_event_loop()
            if loop.is_running():
                loop.create_task(self._http.aclose())
            else:
                loop.run_until_complete(self._http.aclose())
        except RuntimeError:
            pass

    async def aclose(self):
        await self._http.aclose()
        self._http_sync.close()

    # ──────────────────────────────────────────────────────────
    # ERROR HANDLING
    # ──────────────────────────────────────────────────────────

    @staticmethod
    def _handle_error(resp: httpx.Response):
        if resp.is_success:
            return

        code = resp.status_code
        try:
            body = resp.json()
            msg = body.get("detail") or body.get("message") or resp.text
        except Exception:
            msg = resp.text

        if code == 401:
            raise AuthenticationError(str(msg), code)
        if code == 403:
            raise InsufficientScopeError(str(msg), code)
        if code == 404:
            raise NotFoundError(str(msg), code)
        if code == 429:
            retry = int(resp.headers.get("Retry-After", "60"))
            raise RateLimitError(str(msg), retry_after=retry, status_code=code)
        raise TTKIAError(str(msg), code)

    # ──────────────────────────────────────────────────────────
    # RESPONSE PARSING
    # ──────────────────────────────────────────────────────────

    @staticmethod
    def _parse_query_response(data: dict, fallback_query: str = "") -> QueryResponse:
        """Parse backend JSON into a typed QueryResponse."""
        timing_raw = data.get("timing", [])
        if isinstance(timing_raw, dict):
            timing_raw = [{k: v} for k, v in timing_raw.items()]

        # Parse MCP tool results
        mcp_tools_raw = data.get("mcp_tools") or []
        mcp_tools = []
        for t in mcp_tools_raw:
            if isinstance(t, dict):
                mcp_tools.append(MCPToolResult(
                    name=t.get("name", ""),
                    status=t.get("status", ""),
                    args=t.get("args", {}),
                    result=t.get("result"),
                ))

        return QueryResponse(
            success=data.get("success", False),
            conversation_id=data.get("conversation_id", ""),
            message_id=data.get("message_id", ""),
            query=data.get("query", fallback_query),
            response_text=data.get("response_text", ""),
            confidence=data.get("confidence"),
            recommended_response=data.get("recommended_response"),
            query_extended=data.get("query_extended"),
            token_usage=TokenUsage(
                input_tokens=data.get("token_counts", {}).get("input", 0),
                output_tokens=data.get("token_counts", {}).get("output", 0),
            ),
            timing=TimingInfo(raw=timing_raw),
            inferred_environments=data.get("inferred_environments", []),
            docs=[Source(**d) for d in data.get("docs", [])],
            webs=[Source(**w) for w in data.get("webs", [])],
            links=data.get("links", []),
            thinking_process=data.get("thinking_process", []),
            mcp_tools=mcp_tools,
            follow_ups=data.get("follow_ups", []),
            error=data.get("error"),
        )

    # ──────────────────────────────────────────────────────────
    # HEALTH
    # ──────────────────────────────────────────────────────────

    async def ahealth(self) -> HealthStatus:
        """Check TTKIA service health (async)."""
        resp = await self._http.get("/health")
        self._handle_error(resp)
        return HealthStatus(**resp.json())

    def health(self) -> HealthStatus:
        """Check TTKIA service health (sync)."""
        resp = self._http_sync.get("/health")
        self._handle_error(resp)
        return HealthStatus(**resp.json())

    # ──────────────────────────────────────────────────────────
    # QUERY (via /query_complete)
    # ──────────────────────────────────────────────────────────

    async def aquery(
        self,
        query: str,
        *,
        conversation_id: Optional[str] = None,
        prompt: str = "default",
        style: str = "concise",
        web_search: bool = False,
        sources: Optional[List[str]] = None,
        teacher_mode: bool = False,
        title: Optional[str] = None,
    ) -> QueryResponse:
        """Send a query via /query_complete and get the full response (async)."""
        payload = {
            "query": query,
            "prompt": prompt,
            "style": style,
            "web_search": web_search,
            "teacher_mode": teacher_mode,
            "sources": sources or [],
            "attached_files": [],
            "attached_urls": [],
        }
        if conversation_id:
            payload["conversation_id"] = conversation_id
        if title:
            payload["title"] = title

        resp = await self._http.post("/query_complete", json=payload)
        self._handle_error(resp)
        data = resp.json()
        return self._parse_query_response(data, fallback_query=query)

    def query(
        self,
        query: str,
        *,
        conversation_id: Optional[str] = None,
        prompt: str = "default",
        style: str = "concise",
        web_search: bool = False,
        sources: Optional[List[str]] = None,
        teacher_mode: bool = False,
        title: Optional[str] = None,
    ) -> QueryResponse:
        """Send a query via /query_complete and get the full response (sync)."""
        payload = {
            "query": query,
            "prompt": prompt,
            "style": style,
            "web_search": web_search,
            "teacher_mode": teacher_mode,
            "sources": sources or [],
            "attached_files": [],
            "attached_urls": [],
        }
        if conversation_id:
            payload["conversation_id"] = conversation_id
        if title:
            payload["title"] = title

        resp = self._http_sync.post("/query_complete", json=payload)
        self._handle_error(resp)
        data = resp.json()
        return self._parse_query_response(data, fallback_query=query)

    # ──────────────────────────────────────────────────────────
    # CONVERSATIONS
    # ──────────────────────────────────────────────────────────

    async def alist_conversations(self) -> List[ConversationSummary]:
        resp = await self._http.post("/env")
        self._handle_error(resp)
        data = resp.json()
        convs = data.get("user", {}).get("history_chat", {}).get("conversations", [])
        return [ConversationSummary(**c) for c in convs]

    def list_conversations(self) -> List[ConversationSummary]:
        resp = self._http_sync.post("/env")
        self._handle_error(resp)
        data = resp.json()
        convs = data.get("user", {}).get("history_chat", {}).get("conversations", [])
        return [ConversationSummary(**c) for c in convs]

    async def aget_conversation(self, conversation_id: str) -> Conversation:
        resp = await self._http.post(
            "/conversation-info",
            json={"conversation_id": conversation_id},
        )
        self._handle_error(resp)
        return Conversation(**resp.json())

    def get_conversation(self, conversation_id: str) -> Conversation:
        resp = self._http_sync.post(
            "/conversation-info",
            json={"conversation_id": conversation_id},
        )
        self._handle_error(resp)
        return Conversation(**resp.json())

    async def acreate_conversation(self, title: str = "SDK Conversation") -> str:
        resp = await self._http.post(
            "/new-workspace",
            json={"title": title},
        )
        self._handle_error(resp)
        data = resp.json()
        return data.get("conversation_id", "")

    def create_conversation(self, title: str = "SDK Conversation") -> str:
        resp = self._http_sync.post(
            "/new-workspace",
            json={"title": title},
        )
        self._handle_error(resp)
        data = resp.json()
        return data.get("conversation_id", "")

    async def adelete_conversation(self, conversation_id: str) -> bool:
        resp = await self._http.post(
            "/delete-conversation",
            json={"conversation_id": conversation_id},
        )
        self._handle_error(resp)
        return resp.json().get("success", False)

    def delete_conversation(self, conversation_id: str) -> bool:
        resp = self._http_sync.post(
            "/delete-conversation",
            json={"conversation_id": conversation_id},
        )
        self._handle_error(resp)
        return resp.json().get("success", False)

    def export_conversation(self, conversation_id: str, output_path: str):
        resp = self._http_sync.post(
            "/export-conversation",
            json={"conversation_id": conversation_id},
        )
        self._handle_error(resp)
        with open(output_path, "wb") as f:
            f.write(resp.content)

    # ──────────────────────────────────────────────────────────
    # ENVIRONMENTS / PROMPTS / STYLES
    # ──────────────────────────────────────────────────────────

    async def aget_environments(self) -> List[str]:
        resp = await self._http.post("/env")
        self._handle_error(resp)
        return resp.json().get("environment", [])

    def get_environments(self) -> List[str]:
        resp = self._http_sync.post("/env")
        self._handle_error(resp)
        return resp.json().get("environment", [])

    async def aget_prompts(self) -> List[dict]:
        resp = await self._http.post("/env")
        self._handle_error(resp)
        return resp.json().get("prompts", [])

    def get_prompts(self) -> List[dict]:
        resp = self._http_sync.post("/env")
        self._handle_error(resp)
        return resp.json().get("prompts", [])

    async def aget_styles(self) -> List[dict]:
        resp = await self._http.post("/env")
        self._handle_error(resp)
        return resp.json().get("styles", [])

    def get_styles(self) -> List[dict]:
        resp = self._http_sync.post("/env")
        self._handle_error(resp)
        return resp.json().get("styles", [])

    # ──────────────────────────────────────────────────────────
    # FEEDBACK
    # ──────────────────────────────────────────────────────────

    async def asend_feedback(
        self, conversation_id: str, message_id: str, score: int
    ) -> FeedbackResult:
        resp = await self._http.post(
            "/feedback/score",
            json={
                "conversation_id": conversation_id,
                "message_id": message_id,
                "score": score,
            },
        )
        self._handle_error(resp)
        return FeedbackResult(**resp.json())

    def send_feedback(
        self, conversation_id: str, message_id: str, score: int
    ) -> FeedbackResult:
        resp = self._http_sync.post(
            "/feedback/score",
            json={
                "conversation_id": conversation_id,
                "message_id": message_id,
                "score": score,
            },
        )
        self._handle_error(resp)
        return FeedbackResult(**resp.json())